# This is TOML Configuration

[device]
name = "VirtualDevice"
organization = "Developer"
description = "A Virtual Device for development"

[database]
path = "D:\\work\\usbint\\data"

[server]
address = ":8080"

[log]
file = "./usbapi.log"

[shading]
interval = "10s"

[sync]
mode = "shade"
shade_time = "30s"