language: go
go:
  - tip
before_install:
  - sudo rm /etc/apt/sources.list.d/*.list
  - sudo apt-get update -q
  - sudo apt-get install -y build-essential libudev-dev
  - wget https://github.com/libusb/libusb/archive/v1.0.19.tar.gz -O libusb-1.0.19.tar.gz
  - tar -zxvf libusb-1.0.19.tar.gz
  - cd libusb-1.0.19 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install
  - pkg-config --list-all
  - pkg-config --libs libusb-1.0
  - pkg-config --modversion libusb-1.0
  - cd ../ && rm libusb-1.0.19.tar.gz && rm -rf libusb-1.0.19/
  - git clone https://github.com/nodtem66/gousb $GOPATH/src/github.com/kylelemons/gousb
script:
  - go test -v github.com/nodtem66/usbint1/webapi
  - go test -v github.com/nodtem66/usbint1/firmware
  - go test -v github.com/nodtem66/usbint1/event
  - go test -v github.com/nodtem66/usbint1/db