.PHONY: clean All

All:
	@echo "----------Building project:[ test_sqlite3 - Debug ]----------"
	@cd "test_sqlite3" && $(MAKE) -f  "test_sqlite3.mk"
clean:
	@echo "----------Cleaning project:[ test_sqlite3 - Debug ]----------"
	@cd "test_sqlite3" && $(MAKE) -f  "test_sqlite3.mk" clean
