.PHONY: clean All

All:
	@echo "----------Building project:[ usbint1 - Debug ]----------"
	@cd "usbint1" && $(MAKE) -f  "usbint1.mk"
clean:
	@echo "----------Cleaning project:[ usbint1 - Debug ]----------"
	@cd "usbint1" && $(MAKE) -f  "usbint1.mk" clean
