# This is TOML Configuration

[device]
# General infomation about device
name = "VirtualDevice"
organization = "Developer"
description = "A Virtual Device for development"

[database]
# path to store sqlite database file
path = "../usbint/"

[server]
# binding address for backend application
address = ":8080"

[log]
file = "./usbapi.log"

[shading]
interval = "10s"

[sync]
# set scan interval for synchronization
interval = "10s"

# Data Source Name
# [username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
# mysql_dsn = "/db_name"
# mysql_dsn = "root:root@tcp(192.168.59.103:3306)/department1"
mysql_dsn = "/db_name"
# mode = "shade" for shading data without archive to external server
# mode = "sync" for shading data with archive to external server
mode = "shade"

# the data that older than `shade_time` become sync state
shade_time = "10s"